@echo off
echo Cleaning cache and node_modules...

echo Stopping any running processes...
taskkill /f /im node.exe >nul 2>&1

echo Cleaning next.js cache...
rmdir /s /q .next 2>nul
echo Cleaning node_modules cache...
rmdir /s /q node_modules\.cache 2>nul

echo Installing dependencies...
npm ci

echo Starting development server...
npm run dev
