@echo off
echo Starting School Management System...
echo.
echo 1. Starting React development server...
start "React Dev Server" cmd /k "node node_modules/react-scripts/scripts/start.js"
echo.
echo 2. Wait for React server to start, then press any key to start Electron...
pause
echo.
echo 3. Starting Electron application...
node public/electron.js
